export let tagSuggestions: string[] = [
    "Breakfast",
    "Brunch",
    "Lunch",
    "Dinner",
    "Appetizers",
    "Snacks",
    "Desserts",
    "Italian",
    "French",
    "Mexican",
    "Chinese",
    "Indian",
    "Thai",
    "Mediterranean",
    "American",
    "Japanese",
    "Korean",
    "Middle Eastern",
    "Vegetarian",
    "Vegan",
    "Gluten-Free",
    "Dairy-Free",
    "Keto",
    "Paleo",
    "Low-Carb",
    "Low-Fat",
    "Chicken",
    "Beef",
    "Fish/Seafood",
    "Pasta",
    "Rice",
    "Vegetables",
    "Fruits",
    "Beans/Legumes",
    "Grains",
    "Grilling",
    "Baking",
    "Roasting",
    "Sauteing",
    "Steaming",
    "Stir-frying",
    "Slow-cooking",
    "Pressure cooking",
    "Deep-frying",
    "Holiday Recipes",
    "Party/Finger Foods",
    "Picnic Recipes",
    "Barbecue/Grilling Recipes",
    "Potluck Dishes",
    "Beginner Recipes",
    "Intermediate Recipes",
    "Advanced Recipes",
    "Quick and Easy Recipes",
    "One-Pot Meals",
    "Budget-Friendly Recipes",
    "Family-Friendly Recipes",
    "Comfort Food",
    "Gourmet Recipes"
  ]
  
tagSuggestions = tagSuggestions.map(tag => tag.toLowerCase());
